# Generated by Django 6.1 on 2026-08-20 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre comercial')),
                ('slug', models.SlugField(help_text='Identificador del subdominio: <slug>.tudominio.com', unique=True, verbose_name='subdominio')),
                ('logo', models.ImageField(blank=True, upload_to='tenants/logos/')),
                ('primary_color', models.CharField(default='#0f766e', help_text='Hexadecimal, ej: #0f766e', max_length=7, verbose_name='color primario')),
                ('deposit_percentage', models.PositiveSmallIntegerField(default=30, help_text='Porcentaje del total que se cobra como seña (1-100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje de seña')),
                ('mp_access_token', models.CharField(blank=True, help_text='Credencial productiva de la cuenta MP del catering.', max_length=255, verbose_name='access token de MercadoPago')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa (tenant)',
                'verbose_name_plural': 'empresas (tenants)',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='dominio')),
                ('is_primary', models.BooleanField(default=False, verbose_name='es primario')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'dominio',
                'verbose_name_plural': 'dominios',
            },
        ),
    ]
