# Generated by Django 6.1 on 2026-08-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0002_rename_seña_cotizacion_sena'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('mp_payment_id', models.CharField(help_text='Identificador único del pago en MercadoPago.', max_length=100, unique=True, verbose_name='ID de pago MercadoPago')),
                ('mp_preference_id', models.CharField(blank=True, help_text='ID de la preferencia de checkout creada.', max_length=100, verbose_name='ID de preferencia MercadoPago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=15, verbose_name='estado')),
                ('webhook_payload', models.JSONField(blank=True, help_text='Payload completo recibido del webhook para auditoría.', null=True, verbose_name='payload del webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='quotes.cotizacion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
