# Generated by Django 6.1 on 2026-08-20 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField(verbose_name='fecha del evento')),
                ('cantidad_invitados', models.PositiveSmallIntegerField(verbose_name='cantidad de invitados')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('SEÑADA', 'Señada'), ('CONFIRMADA', 'Confirmada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=15, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('seña', models.DecimalField(decimal_places=2, default=0, help_text='Monto de seña calculado según porcentaje del tenant.', max_digits=12, verbose_name='seña')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público para compartir el presupuesto.', unique=True, verbose_name='token público')),
                ('expira_en', models.DateTimeField(blank=True, help_text='Fecha y hora de expiración de la cotización.', null=True, verbose_name='expira el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='quotes.cliente')),
                ('servicio_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='catalog.serviciobase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='tenants.tenant')),
                ('zona_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='catalog.zonaentrega')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, help_text='Precio al momento de crear la cotización.', max_digits=10, verbose_name='precio unitario (snapshot)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.cotizacion')),
            ],
            options={
                'verbose_name': 'ítem de cotización',
                'verbose_name_plural': 'ítems de cotización',
            },
        ),
    ]
