# Generated by Django 6.1 on 2026-08-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='seña',
            new_name='sena',
        ),
    ]
