# Generated by Django 6.1 on 2026-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_seña_cotizacion_sena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('SENADA', 'Señada'), ('CONFIRMADA', 'Confirmada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=15, verbose_name='estado'),
        ),
    ]
