# Generated by Django 6.1 on 2026-08-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0002_rename_seña_cotizacion_sena'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha del evento')),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='CONFIRMADO', max_length=15, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='quotes.cotizacion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FechaReservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha reservada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_reservada', to='bookings.evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_reservadas', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'fecha reservada',
                'verbose_name_plural': 'fechas reservadas',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'fecha'), name='unique_fecha_por_tenant')],
            },
        ),
    ]
