# Generated by Django 6.1 on 2026-08-20 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('tipo_precio', models.CharField(choices=[('FIJO', 'Precio fijo'), ('POR_UNIDAD', 'Por unidad'), ('POR_PERSONA', 'Por persona')], default='FIJO', max_length=15, verbose_name='tipo de precio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'adicional',
                'verbose_name_plural': 'adicionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio por persona')),
                ('capacidad_min', models.PositiveSmallIntegerField(default=10, help_text='Cantidad mínima de invitados para este servicio.', verbose_name='capacidad mínima')),
                ('capacidad_max', models.PositiveSmallIntegerField(default=500, help_text='Cantidad máxima de invitados para este servicio.', verbose_name='capacidad máxima')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_base', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'servicio base',
                'verbose_name_plural': 'servicios base',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre de la zona')),
                ('costo_traslado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo de traslado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_entrega', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'zona de entrega',
                'verbose_name_plural': 'zonas de entrega',
                'ordering': ['nombre'],
            },
        ),
    ]
